// Pre-filled hatch templates for the Quick-add picker. These are
// typical-northeastern defaults: a starting point a guide can tweak for
// their specific water. Windows are conservative/broad — guides should
// narrow them for their river.

export interface HatchTemplate {
  id: string;
  label: string;
  insect: string;
  stage: string;
  time_of_day: string;
  start_month: number;
  start_day: number;
  end_month: number;
  end_day: number;
  peak_start_month: number | null;
  peak_start_day: number | null;
  peak_end_month: number | null;
  peak_end_day: number | null;
  temp_trigger: number | null;
  fly_patterns: string;
  notes: string;
}

// Ordered loosely by season start so the chip strip reads left-to-right
// through the year.
export const HATCH_TEMPLATES: HatchTemplate[] = [
  {
    id: 'winter-midge',
    label: 'Winter Midge',
    insect: 'Winter Midge',
    stage: 'adult',
    time_of_day: 'midday',
    start_month: 12, start_day: 1,
    end_month: 3,    end_day: 31,
    peak_start_month: 1, peak_start_day: 15,
    peak_end_month: 2,   peak_end_day: 28,
    temp_trigger: 38,
    fly_patterns: '#20–24 Griffith\'s Gnat, #22 Zebra Midge, #24 CDC midge',
    notes: 'Tailwaters and spring creeks. Look for slicks and back eddies.',
  },
  {
    id: 'early-black-stone',
    label: 'Early Black Stone',
    insect: 'Early Black Stonefly',
    stage: 'adult',
    time_of_day: 'midday',
    start_month: 3,  start_day: 1,
    end_month: 4,    end_day: 30,
    peak_start_month: 3, peak_start_day: 15,
    peak_end_month: 4,   peak_end_day: 10,
    temp_trigger: 42,
    fly_patterns: '#14–16 black stone adult, #14 Pat\'s Rubber Legs nymph',
    notes: 'Sunny afternoons, look for crawlers on snow along the banks.',
  },
  {
    id: 'bwo',
    label: 'BWO',
    insect: 'Blue-Winged Olive',
    stage: 'dun',
    time_of_day: 'midday',
    start_month: 4,  start_day: 1,
    end_month: 10,   end_day: 30,
    peak_start_month: 4, peak_start_day: 15,
    peak_end_month: 5,   peak_end_day: 15,
    temp_trigger: 50,
    fly_patterns: '#18–20 parachute BWO, #20 CDC emerger, #18 sparkle dun',
    notes: 'Overcast drizzly days produce the strongest emergence.',
  },
  {
    id: 'quill-gordon',
    label: 'Quill Gordon',
    insect: 'Quill Gordon',
    stage: 'dun',
    time_of_day: 'afternoon',
    start_month: 4,  start_day: 15,
    end_month: 5,    end_day: 10,
    peak_start_month: 4, peak_start_day: 20,
    peak_end_month: 5,   peak_end_day: 5,
    temp_trigger: 50,
    fly_patterns: '#14 Quill Gordon dun, #14 hare\'s ear nymph',
    notes: 'Early-season classic. Fish the slow pockets behind boulders.',
  },
  {
    id: 'grannom',
    label: 'Grannom (Apple Caddis)',
    insect: 'Grannom',
    stage: 'adult',
    time_of_day: 'afternoon',
    start_month: 4,  start_day: 15,
    end_month: 5,    end_day: 15,
    peak_start_month: 4, peak_start_day: 20,
    peak_end_month: 5,   peak_end_day: 5,
    temp_trigger: 52,
    fly_patterns: '#14–16 Elk Hair Caddis, #16 LaFontaine Sparkle Pupa',
    notes: 'Swarms along the banks — skate and twitch caddis dries.',
  },
  {
    id: 'hendrickson',
    label: 'Hendrickson',
    insect: 'Hendrickson',
    stage: 'dun',
    time_of_day: 'afternoon',
    start_month: 4,  start_day: 25,
    end_month: 5,    end_day: 25,
    peak_start_month: 5, peak_start_day: 1,
    peak_end_month: 5,   peak_end_day: 15,
    temp_trigger: 52,
    fly_patterns: '#12–14 Hendrickson dun, #14 pheasant tail, Red Quill spinner',
    notes: 'Prime hatch window. Spinner fall at dusk can be epic.',
  },
  {
    id: 'march-brown',
    label: 'March Brown',
    insect: 'March Brown',
    stage: 'dun',
    time_of_day: 'afternoon',
    start_month: 5,  start_day: 15,
    end_month: 6,    end_day: 20,
    peak_start_month: 5, peak_start_day: 25,
    peak_end_month: 6,   peak_end_day: 10,
    temp_trigger: 58,
    fly_patterns: '#12 March Brown dun, #12 hare\'s ear emerger',
    notes: 'Sporadic emergence — fish the dun and emerger together.',
  },
  {
    id: 'sulphur',
    label: 'Sulphur',
    insect: 'Sulphur',
    stage: 'dun',
    time_of_day: 'evening',
    start_month: 5,  start_day: 20,
    end_month: 7,    end_day: 15,
    peak_start_month: 6, peak_start_day: 1,
    peak_end_month: 6,   peak_end_day: 20,
    temp_trigger: 58,
    fly_patterns: '#16 Sulphur dun, #16 CDC emerger, rusty spinner',
    notes: 'Evening emergence. Spinners drop after dark.',
  },
  {
    id: 'isonychia',
    label: 'Isonychia',
    insect: 'Isonychia',
    stage: 'dun',
    time_of_day: 'afternoon',
    start_month: 5,  start_day: 20,
    end_month: 10,   end_day: 1,
    peak_start_month: 6, peak_start_day: 1,
    peak_end_month: 7,   peak_end_day: 1,
    temp_trigger: 60,
    fly_patterns: '#12 Isonychia dun, #10–12 Isonychia nymph swung',
    notes: 'Strong swimmer — swung soft-hackles work well on emergers.',
  },
  {
    id: 'light-cahill',
    label: 'Light Cahill',
    insect: 'Light Cahill',
    stage: 'dun',
    time_of_day: 'evening',
    start_month: 5,  start_day: 25,
    end_month: 7,    end_day: 15,
    peak_start_month: 6, peak_start_day: 10,
    peak_end_month: 6,   peak_end_day: 30,
    temp_trigger: 60,
    fly_patterns: '#14 Light Cahill dun, #14 ginger hackle',
    notes: 'Warm evenings into dusk.',
  },
  {
    id: 'green-drake',
    label: 'Green Drake',
    insect: 'Green Drake',
    stage: 'dun',
    time_of_day: 'evening',
    start_month: 5,  start_day: 25,
    end_month: 6,    end_day: 25,
    peak_start_month: 6, peak_start_day: 1,
    peak_end_month: 6,   peak_end_day: 15,
    temp_trigger: 60,
    fly_patterns: '#8–10 Green Drake dun, coffin fly spinner',
    notes: 'Trophy hatch. Windy evenings bring the best spinner falls.',
  },
  {
    id: 'golden-stone',
    label: 'Golden Stone',
    insect: 'Golden Stonefly',
    stage: 'adult',
    time_of_day: 'evening',
    start_month: 6,  start_day: 1,
    end_month: 7,    end_day: 31,
    peak_start_month: 6, peak_start_day: 15,
    peak_end_month: 7,   peak_end_day: 10,
    temp_trigger: 62,
    fly_patterns: '#8–10 Stimulator, #10 golden stone adult, Pat\'s Rubber Legs',
    notes: 'Crawlers emerge on streamside rocks — watch the shucks.',
  },
  {
    id: 'trico',
    label: 'Trico',
    insect: 'Trico',
    stage: 'spinner',
    time_of_day: 'morning',
    start_month: 7,  start_day: 15,
    end_month: 9,    end_day: 15,
    peak_start_month: 8, peak_start_day: 1,
    peak_end_month: 8,   peak_end_day: 25,
    temp_trigger: null,
    fly_patterns: '#22–24 Trico spinner, #24 CDC dun',
    notes: 'Morning spinner fall in flat water. Fine tippet required.',
  },
  {
    id: 'terrestrials',
    label: 'Terrestrials',
    insect: 'Terrestrials',
    stage: 'adult',
    time_of_day: 'afternoon',
    start_month: 7,  start_day: 1,
    end_month: 10,   end_day: 15,
    peak_start_month: 7, peak_start_day: 20,
    peak_end_month: 9,   peak_end_day: 10,
    temp_trigger: null,
    fly_patterns: '#14–18 ant, #14 beetle, #10–12 hopper, #12 cricket',
    notes: 'Fish the banks and overhanging cover, especially on windy days.',
  },
];
